In [1]:
import pandas as pd

docker run -d --name batch-4-proyecto-container -p 8080:8080 -v /Users/juanpablomunoz/Desktop/Entrega_2_final_proyecto/airflow/Predicciones:/opt/airflow/Predicciones -v /Users/juanpablomunoz/Desktop/Entrega_2_final_proyecto/app/backend/Modelos:/opt/airflow/Modelos batch-4-proyecto

docker build -t batch-4-proyecto .

In [68]:
data_py = pd.read_parquet("predictions_fase_4.parquet")
compraron_pa = data_py[data_py["probabilidad_de_compra"] >= 0.25]
cliente_producto_pa = compraron_pa[["customer_id","product_id"]]
cliente_producto_pa

        customer_id  product_id
119           25743       30500
121           25743       11262
122           25743        1304
125           25743       56714
127           25743        1370
...             ...         ...
172736      2061063       11262
172737      2061063        1304
172740      2061063       56714
172742      2061063        1370
172796      2061063       61542

[3621 rows x 2 columns]

In [69]:
cliente_producto_pa.to_csv("batch_t4.csv", index=False, header=False)

In [21]:
data_csv = pd.read_csv("batch_t2.csv")
data_csv

        25743   1370
0       25743  11262
1       25743   1304
2       25743   1372
3       25743  56714
4       25743  33886
...       ...    ...
4219   457455   1370
4220  2061063   1304
4221  2061063   1370
4222  2061063  11262
4223  2061063  61542

[4224 rows x 2 columns]

In [50]:
data_py_3 = pd.read_parquet("predictions_V2.parquet")
compraron_pa = data_py_3[data_py_3["prediccion_compra"] == 1]
cliente_producto_pa = compraron_pa[["customer_id","product_id"]]
cliente_producto_pa.to_csv("batch_t1.csv", index=False, header=False)

In [ ]:
# top_X = 10  # Número de recomendaciones por cliente
# df_results_batch2 = pd.read_parquet("predictions_fase2.parquet")
# top_predictions1 = df_results_batch2.groupby('customer_id', group_keys=False).apply(
#     lambda x: x.nlargest(top_X, 'probabilidad_de_compra')
# )
# top_predictions = top_predictions1[["customer_id","product_id"]]
# top_predictions.to_csv("top_predictios.csv",index=False, header=False)
# top_predictions

/var/folders/dv/2lkcl0fn3wjgx7zy0djq3pkh0000gn/T/ipykernel_83755/2607262760.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_predictions1 = df_results_batch2.groupby('customer_id', group_keys=False).apply(

        customer_id  product_id
2             25734        1370
3             25734       11262
0             25734        1304
54            25734       61542
4             25734       56714
...             ...         ...
169916      2061063       48574
169872      2061063       33886
169879      2061063       30500
169861      2061063        1372
169918      2061063       50716

[14910 rows x 2 columns]