In [1]:
import pandas as pd

In [16]:
batch3 = pd.read_parquet("batch_t3.parquet")
transacciones_b2 = pd.read_parquet("batch2_transacciones.parquet")
transacciones = pd.read_parquet("transacciones.parquet")

In [17]:
transacciones_b2

        customer_id  product_id  order_id purchase_date     items
0            184605       30500   1271391    2025-01-08  1.666667
1            184605        1370   1271391    2025-01-08  1.666667
2            153867        1372   1275518    2025-01-09  1.000000
3            233091        1370   1276951    2025-01-09  1.666667
4            253683       11262   1286918    2025-01-12  1.666667
...             ...         ...       ...           ...       ...
265404       207330       61364    489755    2024-05-27  1.666667
265405       244971       59396    488047    2024-05-25  3.666667
265406       186657       50716    489529    2024-05-27  3.000000
265407       204243       57414    489725    2024-05-27  1.000000
265408       206748       36720    489748    2024-05-27  3.666667

[265409 rows x 5 columns]

In [18]:
df = pd.concat([batch3, transacciones_b2], ignore_index=True)
df

        customer_id  product_id  order_id purchase_date     items
0            186933       57414   1311205    2025-01-18  1.000000
1            186933       57804   1311205    2025-01-18  1.000000
2            186933       50274   1311205    2025-01-18  1.666667
3            186933       33886   1311205    2025-01-18  5.666667
4            186933       30500   1311205    2025-01-18  5.666667
...             ...         ...       ...           ...       ...
271636       207330       61364    489755    2024-05-27  1.666667
271637       244971       59396    488047    2024-05-25  3.666667
271638       186657       50716    489529    2024-05-27  3.000000
271639       204243       57414    489725    2024-05-27  1.000000
271640       206748       36720    489748    2024-05-27  3.666667

[271641 rows x 5 columns]

In [19]:
df.to_parquet("batch3_transacciones.parquet", index=False)